"""§10 — Reading BandwidthEscrow end-to-end."""
from __future__ import annotations
from ._helpers import md, code


def cells() -> list[dict]:
    return [
        md(
            "## 10. Reading `BandwidthEscrow` end-to-end\n"
            "\n"
            "You now have every piece. Let's read the real contract. Open "
            "[`contracts/src/BandwidthEscrow.sol`](../../contracts/src/BandwidthEscrow.sol) "
            "in a split view and follow along.\n"
            "\n"
            "The contract mediates a swap: a consumer locks ETH, a provider deposits "
            "an NFT, and the contract atomically hands the NFT to the consumer and "
            "the ETH to the provider. State machine:\n"
            "\n"
            "```\n"
            "NONE  --requestAgreement(payable)-->  REQUESTED\n"
            "REQUESTED  --deposit(NFT)-->  ACTIVE\n"
            "REQUESTED  --cancel()-->  CANCELLED\n"
            "```"
        ),
        md(
            "### 10.1 `requestAgreement` — consumer locks ETH\n"
            "\n"
            "```solidity\n"
            "function requestAgreement(\n"
            "    uint256 agreementId, address provider,\n"
            "    uint256 bandwidthMbps, uint256 durationSeconds\n"
            ") external payable {\n"
            "    if (_agreements[agreementId].status != Status.NONE)\n"
            "        revert AgreementAlreadyExists(agreementId);\n"
            "    if (msg.value == 0) revert ZeroPriceNotAllowed();\n"
            "\n"
            "    _agreements[agreementId] = Agreement({\n"
            "        consumer: msg.sender, provider: provider,\n"
            "        bandwidthMbps: bandwidthMbps, durationSeconds: durationSeconds,\n"
            "        priceWei: msg.value,\n"
            "        requestDeadline: block.timestamp + 1 hours,\n"
            "        tokenId: 0, status: Status.REQUESTED\n"
            "    });\n"
            "    emit AgreementRequested(agreementId, msg.sender, provider, bandwidthMbps, durationSeconds, msg.value);\n"
            "}\n"
            "```\n"
            "\n"
            "Line by line, every keyword should now be familiar:\n"
            "\n"
            "- `external payable` — only callable from outside; accepts ETH (§7).\n"
            "- `_agreements[agreementId].status != Status.NONE` — mapping lookup (§7); the default value of a missing key is the zero struct, whose `status` is `NONE` (the first enum variant), so this rejects duplicates.\n"
            "- `revert AgreementAlreadyExists(agreementId)` — custom error with parameters; cheaper than `require` with a string (§7, §6).\n"
            "- `msg.value == 0` — the ETH the caller sent (§7); zero would mean a free agreement, disallowed.\n"
            "- `msg.sender` — the consumer's address, recovered from the tx signature (§3, §7).\n"
            "- `block.timestamp + 1 hours` — anvil/EVM time in seconds; `1 hours = 3600` (§4 timestamps in blocks).\n"
            "- `emit AgreementRequested(...)` — writes a log so the provider can react off-chain (§8).\n"
            "\n"
            "**Why the deadline?** If the provider never deposits, the consumer's "
            "ETH would be stuck. After `requestDeadline`, *anyone* can call "
            "`cancel()` (see 10.3) — a permissionless escape hatch."
        ),
        md(
            "### 10.2 `deposit` — provider settles, atomic swap\n"
            "\n"
            "```solidity\n"
            "function deposit(uint256 agreementId, uint256 tokenId) external {\n"
            "    Agreement storage ag = _agreements[agreementId];\n"
            "\n"
            "    // ── Checks ────────────────────────────────────────────────────\n"
            "    if (ag.status == Status.NONE) revert AgreementNotFound(agreementId);\n"
            "    if (msg.sender != ag.provider) revert NotProvider();\n"
            "    if (ag.status != Status.REQUESTED) revert WrongStatus(ag.status, Status.REQUESTED);\n"
            "\n"
            "    BandwidthNFT.TokenMetadata memory meta = nftContract.getTokenMetadata(tokenId);\n"
            "    if (meta.agreementId != agreementId || ...) revert MetadataMismatch();\n"
            "\n"
            "    // ── Effects ───────────────────────────────────────────────────\n"
            "    ag.status = Status.ACTIVE;\n"
            "    ag.tokenId = tokenId;\n"
            "\n"
            "    // ── Interactions ──────────────────────────────────────────────\n"
            "    nftContract.safeTransferFrom(msg.sender, address(this), tokenId);\n"
            "    nftContract.safeTransferFrom(address(this), ag.consumer, tokenId);\n"
            "    (bool ok,) = ag.provider.call{value: ag.priceWei}(\"\");\n"
            "    if (!ok) revert ETHTransferFailed();\n"
            "\n"
            "    emit AgreementActive(agreementId, tokenId, ag.consumer, ag.provider);\n"
            "}\n"
            "```\n"
            "\n"
            "Two things to notice:\n"
            "\n"
            "**1. `Agreement storage ag = ...` is a reference.** Writes to `ag.status` "
            "mutate the mapping entry directly. If you'd written `Agreement memory ag` "
            "you'd be modifying a local copy and the state change would be lost.\n"
            "\n"
            "**2. Checks → Effects → Interactions.** Status flips to `ACTIVE` "
            "*before* any external call. Why? The low-level `call{value: ...}` "
            "hands control to the provider. If the provider is itself a contract, "
            "its `receive()` function could re-enter `deposit()` for the same "
            "`agreementId`. Because we already set `status = ACTIVE`, the "
            "re-entered call hits `WrongStatus` and reverts. This is the "
            "**reentrancy guard** baked into the function's structure — no extra "
            "library needed.\n"
            "\n"
            "The atomic swap is the two `safeTransferFrom` calls + the ETH `call`: "
            "either everything happens or nothing happens (any revert undoes the whole tx, §6)."
        ),
        md(
            "### 10.3 `cancel` — refund path\n"
            "\n"
            "```solidity\n"
            "function cancel(uint256 agreementId) external {\n"
            "    Agreement storage ag = _agreements[agreementId];\n"
            "    if (ag.status == Status.NONE) revert AgreementNotFound(agreementId);\n"
            "    if (ag.status != Status.REQUESTED) revert WrongStatus(ag.status, Status.REQUESTED);\n"
            "\n"
            "    bool isConsumer = msg.sender == ag.consumer;\n"
            "    bool deadlinePassed = block.timestamp > ag.requestDeadline;\n"
            "    if (!isConsumer && !deadlinePassed) revert DeadlineNotPassed();\n"
            "\n"
            "    address consumer = ag.consumer;\n"
            "    uint256 refund = ag.priceWei;\n"
            "    ag.status = Status.CANCELLED;            // effect before interaction\n"
            "    (bool ok,) = consumer.call{value: refund}(\"\");\n"
            "    if (!ok) revert ETHTransferFailed();\n"
            "    emit AgreementCancelled(agreementId, consumer);\n"
            "}\n"
            "```\n"
            "\n"
            "Two-tier authorization: the consumer can always cancel while "
            "`REQUESTED`; anyone else only after the deadline. Same CEI ordering — "
            "status flipped to `CANCELLED` before the refund leaves the contract.\n"
            "\n"
            "---\n"
            "\n"
            "**You're done.** The reference doc you'll want open while reading "
            "future contracts is [01a — chain contract model](../01a_chain_contract_model.py), "
            "and the lifecycle walkthrough is [01b — escrow lifecycle](../01b_chain_escrow_lifecycle.py)."
        ),
    ]
